### ISSUE TITLE
<not an issue>

### ISSUE THREAD

**Issue by IshanJ25** [Akascape/Akascape#5]
Hi, this is not an issue, just out of curiosity:

I noticed this snake contribution animation on your profile, and was wondering if you have copied it from my profile workflow:

https://github.com/Akascape/Akascape/blob/main/.github/workflows/snek.yml
https://github.com/IshanJ25/IshanJ25/blob/83de6e117d21ff0872171c1e1a47569ea7ff4ae9/.github/workflows/make_snek.yml

just asking, no problem or anything, since the color codes also exactly match up

**Comment by Akascape** [comment]
@IshanJ25 Yes I guess, was impressed by it, so copied the workflow. I hope you will not have any problem.
I just wanted to make my profile unique.

**Comment by IshanJ25** [comment]
> I hope you will not have any problem.
not at all

**Comment by Akascape** [comment]
@IshanJ25 I have updated the colors :)

**Comment by IshanJ25** [comment]
@Akascape nice
I have been working on some new themes for the same myself too, will update soon on my repo

**Comment by Akascape** [comment]
@IshanJ25 Amazing, please let me know if you get some more profile material like this.
